# GitHub Repository Settings
# https://probot.github.io/apps/settings/

repository:
  name: nextjs-portfolio-blog-research
  description: 🚀 Portfolio with Blog Template for Next.js 16 with App Router, Tailwind CSS 4, TypeScript and SEO 📚 Optimized for Researcher, Developer, Designer and More ✨
  homepage: https://www.zangwei.dev/open-source/nextjs-portfolio-blog-research/docs
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: ffffff
    description: This will not be worked on

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      enforce_admins: false
      required_linear_history: true
      restrictions: null
